####
GET http://localhost:3000/ping

####
GET http://localhost:3000/task1?key=type&value=socks

####
GET http://localhost:3000/task2

####
GET http://localhost:3000/task3

####
POST http://localhost:3000/add-goods

{
    "newGoods": [
                {"type": "socks", "color": "red", "quantity": 10, "priceForPair": "$3"}
    ]
}

####
POST http://localhost:3000/source

{
    "source": "store"
}