####
GET http://localhost:3000/ping

####
GET http://localhost:3000/

####
POST http://localhost:3000/comment?test=hi

{
    "json": "body"
}

####
GET http://localhost:3000/task1?key=type&vallue=socks

####
GET http://localhost:3000/task2

####
GET http://localhost:3000/task3

####
POST http://localhost:3000/add-goods

{
    "newGoods": [
                {"type": "socks", "color": "red", "quantity": 10, "priceForPair": "$3"}
    ]
}